language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb -y
  - sudo rethinkdb &
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
after_script:
  - killall rethinkdb
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
