sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
  - npm i -g npm@^3.0.0
before_script:
  - sudo rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 10
  - npm prune
script:
  - rethinkdb
  - npm run test
after_success:
  - npm run semantic-release
after_script:
  - killall rethinkdb
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
